import type { Metadata } from 'next';
import { Noto_Sans_Mono } from 'next/font/google';
import './globals.css';
import { TopMenu } from '@/components/layout/TopMenu';
import { Footer } from '@/components/layout/Footer';
import { ThemeProvider } from 'next-themes';

const notoSansMono = Noto_Sans_Mono({
  subsets: ['latin'],
  variable: '--font-geist',
});

export const metadata: Metadata = {
  title: 'Wonder Toolbox',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={notoSansMono.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <TopMenu />
          <main className='min-h-screen flex flex-col'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
