import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';

import './globals.css';

import { Noto_Sans_Mono } from 'next/font/google';

import { Footer } from '@/components/layout/Footer';
import { TopMenu } from '@/components/layout/TopMenu';

const notoSansMono = Noto_Sans_Mono({
  subsets: ['latin'],
  variable: '--font-noto-sans-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Wonder Toolbox',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={notoSansMono.className}>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TopMenu />
          <main className="flex-1">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
